config/routes.rb
Rails.application.routes.draw do
  resources :items, only: [:index, :create, :destroy]
  root 'items#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
    @cart_items = Item.where(in_cart: true)
  end

  def create
    @item = Item.new(item_params)
    @item.in_cart = true # Actualiza el atributo in_cart
    if @item.save
      redirect_to root_path, notice: 'Item agregado a la lista.'
    else
      @items = Item.all
      render :index
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to root_path, notice: 'Item eliminado de la lista.'
  end

  private

  def item_params
    params.require(:item).permit(:name, :quantity)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with model: @item, url: items_path, local: true do |form| %>
  <%= form.label :name, 'Ingrediente' %>
  <%= form.text_field :name, name: 'item[name]' %>

  <%= form.label :quantity, 'Cantidad' %>
  <%= form.number_field :quantity, name: 'item[quantity]' %>

  <%= form.submit 'Agregar a la lista' %>
<% end %>

app/views/items/index.html.erb
<h1>Lista de Supermercado</h1>

<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>

<ul>
  <% @items.each do |item| %>
    <li>
      <%= item.name %>
      <%= item.quantity %> unidades
      <%= link_to 'Eliminar', item, method: :delete, data: { confirm: '¿Estás seguro?' } %>
    </li>
  <% end %>
</ul>

<%= render 'form' %>

<h1>Carrito</h1>

<ul>
  <% @cart_items.each do |item| %>
    <li>
      <%= item.name %>
      <%= item.quantity %> unidades
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ListaSupermercado</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>